# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9514829638d51a9f534d24aa1e3f457352f2f29325806575d5b81e8001845dd0a58a8554ebeec577e462e71b58bdd80b471fae503faf5714ca3c45a10e7a6fb9

test:
  secret_key_base: 248dd01db26393cb051f516200d3acff3bb95bdffafd438d66e8e43aef6c96a39f592689d5c7cfffb1635c5831dce85713e82d1a24c830df4327415e800ec173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
